- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/ala/bie/AdminController.groovy
- grails-app/controllers/au/org/ala/bie/SearchController.groovy
- grails-app/views/index.gsp
- test/unit/au/org/ala/bie/AdminControllerSpec.groovy
- test/unit/au/org/ala/bie/ImportServiceSpec.groovy
- test/unit/au/org/ala/bie/SearchControllerSpec.groovy
Also:
Include default image URL sources in config
Add extra ws calls to index
> Fix format errors in controller specs

- grails-app/services/au/org/ala/bie/ImportService.groovy
- grails-app/services/au/org/ala/bie/SearchService.groovy
- grails-app/views/import/index.gsp
- test/scripts/hammer.sh
Import names and identifiers from DwCAs without taxa being specified in the same file.
> Import "base" vernacular names and identifiers

- build.gradle
from ala-name-matching library causing grails problems
> Stop problems with imported validation libraries

- build.gradle
- doc/nameology/afd.md
- doc/nameology/apni.md
- doc/nameology/ausmoss.md
- doc/nameology/caab.md
- doc/nameology/conventions.md
- doc/nameology/processing-basics.md
- grails-app/conf/vernacularNameStatus.json
- grails-app/services/au/org/ala/bie/ImportService.groovy
- grails-app/services/au/org/ala/bie/SearchService.groovy
- src/test/groovy/au/org/ala/bie/ImportServicesControllerSpec.groovy
- src/test/groovy/au/org/ala/bie/JobControllerSpec.groovy
Update documentation
Add field list for search calls
Additional fields supporting GBIF vernacular names extension
> Vernacular extensions

- build.gradle
- grails-app/services/au/org/ala/bie/ImportService.groovy
Fix index out of bounds error on formatted name construction
Move to version of ala-auth compatible with CAS on oztaxa
> Version 1.4.2.2

- grails-app/services/au/org/ala/bie/SearchService.groovy
Better fix, works for both ansible script and defaults defined in application.yml
(sorry, should have checked this yesterday!)
> bq and hl parameters accept array or string

- build.gradle
- doc/nameology/conventions.md
- grails-app/assets/javascripts/swagger-ui.js
- grails-app/assets/stylesheets/swagger-ui.css
- grails-app/controllers/au/org/ala/bie/AdminController.groovy
- grails-app/controllers/au/org/ala/bie/ImportController.groovy
- grails-app/controllers/au/org/ala/bie/JobController.groovy
- grails-app/controllers/au/org/ala/bie/SearchController.groovy
- grails-app/views/index.gsp
- src/main/resources/public/openapi.yml
Replace front page documentation with openapi specificatio and swagger-ui display
> OpenAPI Documentation

- grails-app/services/au/org/ala/bie/ImportService.groovy
Things with an & in the name were not correctly searching
> Correct name search for escapeable characters

- grails-app/controllers/au/org/ala/bie/SearchController.groovy
- grails-app/services/au/org/ala/bie/SearchService.groovy
See https://github.com/AtlasOfLivingAustralia/bie-index/issues/239
> Fix for image search failing

- README.md
- grails-app/conf/application.yml
- grails-app/conf/default-favourites.json
- grails-app/conf/default-weights.json
- grails-app/controllers/au/org/ala/bie/ImportController.groovy
- grails-app/i18n/messages.properties
- grails-app/services/au/org/ala/bie/ImportService.groovy
- grails-app/services/au/org/ala/bie/SearchService.groovy
- grails-app/views/import/links.gsp
- src/main/groovy/au/org/ala/bie/indexing/WeightBuilder.groovy
- src/main/resources/public/openapi.yml
- src/test/groovy/au/org/ala/bie/indexing/WeightBuilderSpec.groovy
- src/test/resources/au/org/ala/bie/indexing/common-weights.json
Provide images for common names.
> Provide lists of favourites so that popular species get listed first.

- grails-app/services/au/org/ala/bie/ImportService.groovy
Since they should go to the taxon itself.
> Don't provide link identifiers for common names

- .travis.yml
- build.gradle
- grails-app/conf/application.yml
- grails-app/services/au/org/ala/bie/ImportService.groovy
- grails-app/services/au/org/ala/bie/WordpressService.groovy
- src/test/groovy/au/org/ala/bie/WordPressServiceSpec.groovy
Changes to allow complete crawling of a wordpress site
> Release 1.4.7

- grails-app/controllers/au/org/ala/bie/MiscController.groovy
- grails-app/services/au/org/ala/bie/ImportService.groovy
See https://github.com/AtlasOfLivingAustralia/bie-index/issues/262
Make preferred image update use the online solr index
Return correct status for preferred image update
> Ensure preferred image works

- grails-app/init/bie/index/BootStrap.groovy
Use of external resources packaged by:
https://github.com/living-atlases/ala-i18n
Other [similar PRs](https://github.com/search?q=is%3Apr+author%3Avjrj+org%3AAtlasOfLivingAustralia+ala-i18n+external&type=Issues).
> Usage of external ala-i18n resources

- grails-app/controllers/au/org/ala/bie/SearchController.groovy
https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/542
> Fix for download without parameters problem

- grails-app/services/au/org/ala/bie/SearchService.groovy
- src/main/resources/public/openapi.yml
And improve swagger connection
> Fix image config paths

- grails-app/controllers/au/org/ala/bie/ImportController.groovy
- grails-app/services/au/org/ala/bie/ImportService.groovy
- grails-app/services/au/org/ala/bie/IndexService.groovy
- grails-app/views/import/collectory.gsp
- grails-app/views/import/knowledgebase.gsp
- grails-app/views/import/layers.gsp
- grails-app/views/import/localities.gsp
- grails-app/views/import/regions.gsp
- grails-app/views/import/wordpress.gsp
- src/main/resources/public/openapi.yml
Fix for issue https://github.com/AtlasOfLivingAustralia/bie-index/issues/300
Updates can be triggered via existing API
> Allow articles, layers and collectory to be refreshed online

- grails-app/controllers/au/org/ala/bie/SearchController.groovy
- src/main/resources/public/openapi.yml
> Deal with extra parameters in childConcepts API call.

- build.gradle
- grails-app/init/bie/index/Application.groovy
- grails-app/services/au/org/ala/bie/SearchService.groovy
- src/main/groovy/au/org/ala/bie/solr/SolrClientBean.groovy
- src/test/groovy/au/org/ala/bie/solr/SolrClientBeanSpec.groovy
Upgrade to latest namematching library and solr version
Don't autoconfigure SOLR
> Fix for https://github.com/AtlasOfLivingAustralia/bie-index/issues/318

- build.gradle
- grails-app/services/au/org/ala/bie/ImportService.groovy
- grails-app/services/au/org/ala/bie/IndexService.groovy
Fix error in adding boost to updated solr. It's not used any more, so remvoed.
> Update snapshot version

- build.gradle
- grails-app/controllers/au/org/ala/bie/SearchController.groovy
- grails-app/services/au/org/ala/bie/IndexService.groovy
- grails-app/services/au/org/ala/bie/SearchService.groovy
- src/main/resources/public/openapi.yml
- src/test/groovy/au/org/ala/bie/SearchControllerSpec.groovy
Fix for #327 
Name search is more parsimonious about what constitutes a match and (one would expect) more accurate.
> Hotfix 327

- src/main/resources/public/openapi.yml
Includes various changes - mainly adding description attribute to response definitions
> Fixes for #331 - openapi validation

- build.gradle
- grails-app/services/au/org/ala/bie/SearchService.groovy
Fixes for #327 to catch the other cases where a broad search is being erroneously used.
> Further fixes for issue #327

- grails-app/controllers/au/org/ala/bie/SearchController.groovy
- grails-app/controllers/bie/index/UrlMappings.groovy
- grails-app/services/au/org/ala/bie/SearchService.groovy
- src/main/resources/public/openapi.yml
> Bulk image lookup API call

- build.gradle
Adding back `group` to build.gradle removed during merge
> Develop to Master second PR

- grails-app/conf/application.yml
- grails-app/controllers/au/org/ala/bie/ImportController.groovy
- grails-app/controllers/au/org/ala/bie/SearchController.groovy
- grails-app/i18n/messages.properties
- grails-app/services/au/org/ala/bie/ImportService.groovy
- grails-app/services/au/org/ala/bie/NameService.groovy
- grails-app/services/au/org/ala/bie/SearchService.groovy
- grails-app/views/import/links.gsp
Do not merge until 3.1.0 is released.
> #373 align common name with namematching-service

- grails-app/services/au/org/ala/bie/ImportService.groovy
- grails-app/services/au/org/ala/bie/SearchService.groovy
> 386 fix wikiurl import
